version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  proxy:
    image: nginx:1-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_internal.conf:/etc/nginx/nginx.conf:ro,Z
    restart: always
    logging: *default-logging
    depends_on:
      - torrents-csv
      - torrents-csv-leptos

  torrents-csv:
    image: dessalines/torrents-csv-server:latest
    hostname: torrents-csv
    ports:
      - "8902:8902"
    restart: always
    logging: *default-logging
    environment:
      - TORRENTS_CSV_DB_FILE=/app/torrents.db

  torrents-csv-leptos:
    image: dessalines/torrents-csv-leptos:latest
    restart: always
    logging: *default-logging
    environment:
      - RUST_LOG="warn"
      - TORRENTS_CSV_ENDPOINT=http://torrents-csv:8902
